"""Initial schema with all tables

Revision ID: 001_initial
Revises: 
Create Date: 2024-11-12

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    # Reference tables
    op.create_table('competitions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('statsbomb_competition_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('season', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_competitions')),
        sa.UniqueConstraint('statsbomb_competition_id', name=op.f('uq_competitions_statsbomb_competition_id')),
        sa.UniqueConstraint('statsbomb_competition_id', 'season', name='uq_competition_season')
    )
    op.create_index('ix_competitions_name_season', 'competitions', ['name', 'season'], unique=False)

    op.create_table('teams',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('statsbomb_team_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
        sa.UniqueConstraint('statsbomb_team_id', name=op.f('uq_teams_statsbomb_team_id'))
    )

    op.create_table('players',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('statsbomb_player_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('position', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
        sa.UniqueConstraint('statsbomb_player_id', name=op.f('uq_players_statsbomb_player_id'))
    )

    # Match data tables
    op.create_table('matches',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('statsbomb_match_id', sa.Integer(), nullable=False),
        sa.Column('competition_id', sa.Integer(), nullable=False),
        sa.Column('home_team_id', sa.Integer(), nullable=False),
        sa.Column('away_team_id', sa.Integer(), nullable=False),
        sa.Column('kickoff_time', sa.DateTime(), nullable=True),
        sa.Column('match_date', sa.DateTime(), nullable=True),
        sa.Column('season', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_matches_competition_id_competitions')),
        sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams')),
        sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
        sa.UniqueConstraint('statsbomb_match_id', name=op.f('uq_matches_statsbomb_match_id'))
    )
    op.create_index('ix_matches_competition_id', 'matches', ['competition_id'], unique=False)

    op.create_table('raw_events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('match_id', sa.Integer(), nullable=False),
        sa.Column('statsbomb_event_id', sa.String(length=100), nullable=False),
        sa.Column('raw_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('period', sa.Integer(), nullable=False),
        sa.Column('minute', sa.Integer(), nullable=False),
        sa.Column('second', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_raw_events_match_id_matches')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_events')),
        sa.UniqueConstraint('match_id', 'statsbomb_event_id', name='uq_raw_event')
    )
    op.create_index('ix_raw_events_match_id', 'raw_events', ['match_id'], unique=False)
    op.create_index('ix_raw_events_type', 'raw_events', ['type'], unique=False)

    op.create_table('possessions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('match_id', sa.Integer(), nullable=False),
        sa.Column('possession_number', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('start_event_id', sa.Integer(), nullable=True),
        sa.Column('end_event_id', sa.Integer(), nullable=True),
        sa.Column('start_minute', sa.Integer(), nullable=True),
        sa.Column('end_minute', sa.Integer(), nullable=True),
        sa.Column('duration_seconds', sa.Float(), nullable=True),
        sa.Column('event_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_possessions_match_id_matches')),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_possessions_team_id_teams')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_possessions')),
        sa.UniqueConstraint('match_id', 'possession_number', name='uq_possession')
    )
    op.create_index('ix_possessions_match_id', 'possessions', ['match_id'], unique=False)
    op.create_index('ix_possessions_team_id', 'possessions', ['team_id'], unique=False)

    op.create_table('events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('raw_event_id', sa.Integer(), nullable=False),
        sa.Column('match_id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=True),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('period', sa.Integer(), nullable=False),
        sa.Column('minute', sa.Integer(), nullable=False),
        sa.Column('second', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.String(length=20), nullable=True),
        sa.Column('possession', sa.Integer(), nullable=True),
        sa.Column('location_x', sa.Float(), nullable=True),
        sa.Column('location_y', sa.Float(), nullable=True),
        sa.Column('under_pressure', sa.Boolean(), nullable=False),
        sa.Column('outcome', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_events_match_id_matches')),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_events_player_id_players')),
        sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], name=op.f('fk_events_raw_event_id_raw_events')),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_events_team_id_teams')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_match_id', 'events', ['match_id'], unique=False)
    op.create_index('ix_events_match_possession', 'events', ['match_id', 'possession'], unique=False)
    op.create_index('ix_events_team_id', 'events', ['team_id'], unique=False)
    op.create_index('ix_events_type', 'events', ['type'], unique=False)

    # Shot tables
    op.create_table('shots',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('match_id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=True),
        sa.Column('opponent_team_id', sa.Integer(), nullable=False),
        sa.Column('statsbomb_xg', sa.Float(), nullable=True),
        sa.Column('body_part', sa.String(length=50), nullable=True),
        sa.Column('technique', sa.String(length=50), nullable=True),
        sa.Column('shot_type', sa.String(length=50), nullable=True),
        sa.Column('outcome', sa.String(length=50), nullable=False),
        sa.Column('first_time', sa.Boolean(), nullable=False),
        sa.Column('is_blocked', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_shots_event_id_events')),
        sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_shots_match_id_matches')),
        sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], name=op.f('fk_shots_opponent_team_id_teams')),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_shots_player_id_players')),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_shots_team_id_teams')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_shots')),
        sa.UniqueConstraint('event_id', name=op.f('uq_shots_event_id'))
    )
    op.create_index('ix_shots_match_id', 'shots', ['match_id'], unique=False)
    op.create_index('ix_shots_opponent_team_id', 'shots', ['opponent_team_id'], unique=False)
    op.create_index('ix_shots_team_id', 'shots', ['team_id'], unique=False)

    op.create_table('shot_features',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('shot_id', sa.Integer(), nullable=False),
        sa.Column('version_tag', sa.String(length=20), nullable=False),
        sa.Column('shot_distance', sa.Float(), nullable=True),
        sa.Column('shot_angle', sa.Float(), nullable=True),
        sa.Column('centrality', sa.Float(), nullable=True),
        sa.Column('distance_to_goal_line', sa.Float(), nullable=True),
        sa.Column('score_diff_at_shot', sa.Integer(), nullable=True),
        sa.Column('is_leading', sa.Boolean(), nullable=False),
        sa.Column('is_trailing', sa.Boolean(), nullable=False),
        sa.Column('is_drawing', sa.Boolean(), nullable=False),
        sa.Column('minute_bucket', sa.String(length=20), nullable=True),
        sa.Column('possession_sequence_length', sa.Integer(), nullable=True),
        sa.Column('possession_duration', sa.Float(), nullable=True),
        sa.Column('previous_action_gap', sa.Float(), nullable=True),
        sa.Column('recent_def_actions_count', sa.Integer(), nullable=False),
        sa.Column('pressure_proxy_score', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_shot_features_shot_id_shots')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_features')),
        sa.UniqueConstraint('shot_id', name=op.f('uq_shot_features_shot_id'))
    )
    op.create_index('ix_shot_features_version_tag', 'shot_features', ['version_tag'], unique=False)

    # Opponent profiles
    op.create_table('opponent_def_profile',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('version_tag', sa.String(length=20), nullable=False),
        sa.Column('zone_id', sa.String(length=10), nullable=True),
        sa.Column('global_rating', sa.Float(), nullable=True),
        sa.Column('block_rate', sa.Float(), nullable=True),
        sa.Column('zone_rating', sa.Float(), nullable=True),
        sa.Column('shots_sample', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_opponent_def_profile_team_id_teams')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_opponent_def_profile')),
        sa.UniqueConstraint('team_id', 'version_tag', 'zone_id', name='uq_opponent_profile')
    )
    op.create_index('ix_opponent_profile_team_version', 'opponent_def_profile', ['team_id', 'version_tag'], unique=False)

    # Model registry
    op.create_table('model_registry',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('algorithm', sa.String(length=100), nullable=False),
        sa.Column('hyperparams', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('trained_on_version_tag', sa.String(length=20), nullable=False),
        sa.Column('artifact_path', sa.Text(), nullable=False),
        sa.Column('calibration_metrics', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_model_registry')),
        sa.UniqueConstraint('model_name', 'version', name='uq_model_version')
    )
    op.create_index('ix_model_registry_name_version', 'model_registry', ['model_name', 'version'], unique=False)

    # Predictions
    op.create_table('shot_predictions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('shot_id', sa.Integer(), nullable=False),
        sa.Column('model_id', sa.Integer(), nullable=False),
        sa.Column('version_tag', sa.String(length=20), nullable=False),
        sa.Column('is_neutralized', sa.Boolean(), nullable=False),
        sa.Column('raw_probability', sa.Float(), nullable=False),
        sa.Column('neutral_probability', sa.Float(), nullable=True),
        sa.Column('opponent_adjusted_diff', sa.Float(), nullable=True),
        sa.Column('opponent_adjusted_ratio', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], name=op.f('fk_shot_predictions_model_id_model_registry')),
        sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_shot_predictions_shot_id_shots')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_predictions')),
        sa.UniqueConstraint('shot_id', 'model_id', 'is_neutralized', name='uq_shot_prediction')
    )
    op.create_index('ix_shot_predictions_model_id', 'shot_predictions', ['model_id'], unique=False)
    op.create_index('ix_shot_predictions_shot_id', 'shot_predictions', ['shot_id'], unique=False)

    # Aggregates
    op.create_table('aggregates_player',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=False),
        sa.Column('model_id', sa.Integer(), nullable=False),
        sa.Column('version_tag', sa.String(length=20), nullable=False),
        sa.Column('shots_count', sa.Integer(), nullable=False),
        sa.Column('summed_cxg', sa.Float(), nullable=False),
        sa.Column('summed_neutral_cxg', sa.Float(), nullable=False),
        sa.Column('summed_oppadj_diff', sa.Float(), nullable=False),
        sa.Column('avg_oppadj_diff', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], name=op.f('fk_aggregates_player_model_id_model_registry')),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_aggregates_player_player_id_players')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_aggregates_player')),
        sa.UniqueConstraint('player_id', 'model_id', 'version_tag', name='uq_player_aggregate')
    )
    op.create_index('ix_aggregates_player_model_id', 'aggregates_player', ['model_id'], unique=False)

    op.create_table('aggregates_team',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('model_id', sa.Integer(), nullable=False),
        sa.Column('version_tag', sa.String(length=20), nullable=False),
        sa.Column('shots_count', sa.Integer(), nullable=False),
        sa.Column('summed_cxg', sa.Float(), nullable=False),
        sa.Column('summed_neutral_cxg', sa.Float(), nullable=False),
        sa.Column('summed_oppadj_diff', sa.Float(), nullable=False),
        sa.Column('avg_oppadj_diff', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], name=op.f('fk_aggregates_team_model_id_model_registry')),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_aggregates_team_team_id_teams')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_aggregates_team')),
        sa.UniqueConstraint('team_id', 'model_id', 'version_tag', name='uq_team_aggregate')
    )
    op.create_index('ix_aggregates_team_model_id', 'aggregates_team', ['model_id'], unique=False)

    # Evaluation
    op.create_table('evaluation_metrics',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('model_id', sa.Integer(), nullable=False),
        sa.Column('metric_name', sa.String(length=100), nullable=False),
        sa.Column('metric_value', sa.Float(), nullable=False),
        sa.Column('slice_name', sa.String(length=100), nullable=True),
        sa.Column('slice_filter', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], name=op.f('fk_evaluation_metrics_model_id_model_registry')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_metrics'))
    )
    op.create_index('ix_evaluation_metrics_metric_name', 'evaluation_metrics', ['metric_name'], unique=False)
    op.create_index('ix_evaluation_metrics_model_id', 'evaluation_metrics', ['model_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index('ix_evaluation_metrics_model_id', table_name='evaluation_metrics')
    op.drop_index('ix_evaluation_metrics_metric_name', table_name='evaluation_metrics')
    op.drop_table('evaluation_metrics')
    op.drop_index('ix_aggregates_team_model_id', table_name='aggregates_team')
    op.drop_table('aggregates_team')
    op.drop_index('ix_aggregates_player_model_id', table_name='aggregates_player')
    op.drop_table('aggregates_player')
    op.drop_index('ix_shot_predictions_shot_id', table_name='shot_predictions')
    op.drop_index('ix_shot_predictions_model_id', table_name='shot_predictions')
    op.drop_table('shot_predictions')
    op.drop_index('ix_model_registry_name_version', table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index('ix_opponent_profile_team_version', table_name='opponent_def_profile')
    op.drop_table('opponent_def_profile')
    op.drop_index('ix_shot_features_version_tag', table_name='shot_features')
    op.drop_table('shot_features')
    op.drop_index('ix_shots_team_id', table_name='shots')
    op.drop_index('ix_shots_opponent_team_id', table_name='shots')
    op.drop_index('ix_shots_match_id', table_name='shots')
    op.drop_table('shots')
    op.drop_index('ix_events_type', table_name='events')
    op.drop_index('ix_events_team_id', table_name='events')
    op.drop_index('ix_events_match_possession', table_name='events')
    op.drop_index('ix_events_match_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_possessions_team_id', table_name='possessions')
    op.drop_index('ix_possessions_match_id', table_name='possessions')
    op.drop_table('possessions')
    op.drop_index('ix_raw_events_type', table_name='raw_events')
    op.drop_index('ix_raw_events_match_id', table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_index('ix_matches_competition_id', table_name='matches')
    op.drop_table('matches')
    op.drop_table('players')
    op.drop_table('teams')
    op.drop_index('ix_competitions_name_season', table_name='competitions')
    op.drop_table('competitions')
    # ### end Alembic commands ###
