"""add event type tables

Revision ID: 14f289cc51b0
Revises: 2b70afefcdee
Create Date: 2025-11-13 11:54:21.114303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f289cc51b0'
down_revision: Union[str, Sequence[str], None] = '2b70afefcdee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ball_receipts',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('clean_receipt', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ball_receipts_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ball_receipts')),
    sa.UniqueConstraint('event_id', name=op.f('uq_ball_receipts_event_id'))
    )
    op.create_index('ix_ball_receipts_event_id', 'ball_receipts', ['event_id'], unique=False)
    op.create_table('blocks',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=True),
    sa.Column('is_deflection', sa.Boolean(), nullable=False),
    sa.Column('is_save_block', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_blocks_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocks')),
    sa.UniqueConstraint('event_id', name=op.f('uq_blocks_event_id'))
    )
    op.create_index('ix_blocks_event_id', 'blocks', ['event_id'], unique=False)
    op.create_table('carries',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('start_x', sa.Float(), nullable=True),
    sa.Column('start_y', sa.Float(), nullable=True),
    sa.Column('end_x', sa.Float(), nullable=True),
    sa.Column('end_y', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_carries_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carries')),
    sa.UniqueConstraint('event_id', name=op.f('uq_carries_event_id'))
    )
    op.create_index('ix_carries_event_id', 'carries', ['event_id'], unique=False)
    op.create_table('clearances',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('body_part', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('under_pressure', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_clearances_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clearances')),
    sa.UniqueConstraint('event_id', name=op.f('uq_clearances_event_id'))
    )
    op.create_index('ix_clearances_event_id', 'clearances', ['event_id'], unique=False)
    op.create_table('dribbles',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('overrun', sa.Boolean(), nullable=False),
    sa.Column('nutmeg', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_dribbles_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dribbles')),
    sa.UniqueConstraint('event_id', name=op.f('uq_dribbles_event_id'))
    )
    op.create_index('ix_dribbles_event_id', 'dribbles', ['event_id'], unique=False)
    op.create_table('duels',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('duel_type', sa.String(length=100), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_duels_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duels')),
    sa.UniqueConstraint('event_id', name=op.f('uq_duels_event_id'))
    )
    op.create_index('ix_duels_event_id', 'duels', ['event_id'], unique=False)
    op.create_table('interceptions',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_interceptions_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interceptions')),
    sa.UniqueConstraint('event_id', name=op.f('uq_interceptions_event_id'))
    )
    op.create_index('ix_interceptions_event_id', 'interceptions', ['event_id'], unique=False)
    op.create_table('passes',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.Column('pass_height', sa.String(length=50), nullable=True),
    sa.Column('pass_type', sa.String(length=100), nullable=True),
    sa.Column('body_part', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('recipient_player_id', sa.Integer(), nullable=True),
    sa.Column('is_cross', sa.Boolean(), nullable=False),
    sa.Column('is_through_ball', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_passes_event_id_events')),
    sa.ForeignKeyConstraint(['recipient_player_id'], ['players.id'], name=op.f('fk_passes_recipient_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passes')),
    sa.UniqueConstraint('event_id', name=op.f('uq_passes_event_id'))
    )
    op.create_index('ix_passes_event_id', 'passes', ['event_id'], unique=False)
    op.create_table('pressures',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_pressures_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pressures')),
    sa.UniqueConstraint('event_id', name=op.f('uq_pressures_event_id'))
    )
    op.create_index('ix_pressures_event_id', 'pressures', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pressures_event_id', table_name='pressures')
    op.drop_table('pressures')
    op.drop_index('ix_passes_event_id', table_name='passes')
    op.drop_table('passes')
    op.drop_index('ix_interceptions_event_id', table_name='interceptions')
    op.drop_table('interceptions')
    op.drop_index('ix_duels_event_id', table_name='duels')
    op.drop_table('duels')
    op.drop_index('ix_dribbles_event_id', table_name='dribbles')
    op.drop_table('dribbles')
    op.drop_index('ix_clearances_event_id', table_name='clearances')
    op.drop_table('clearances')
    op.drop_index('ix_carries_event_id', table_name='carries')
    op.drop_table('carries')
    op.drop_index('ix_blocks_event_id', table_name='blocks')
    op.drop_table('blocks')
    op.drop_index('ix_ball_receipts_event_id', table_name='ball_receipts')
    op.drop_table('ball_receipts')
    # ### end Alembic commands ###
